### ISSUE TITLE
Exception concerning depscan metrics

### ISSUE THREAD

**Issue by gitnachogo** [ShiftLeftSecurity/sast-scan#247]
Hi!
I've just got this error trying to scan a project using depscan as one of the chosen tools:
```
╭─────────────────────────────────────────────────────────── Recommendation ───────────────────────────────────────────────────────────╮
 │ ✅ No package requires immediate attention since the major vulnerabilities are found only in dev packages and indirect dependencies. │
 ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
 [11:33:57] DEBUG    Depscan and HTML report written to file: /builds/platform/common/xxx/reports/depscan-report-java.json,         
                     /builds/platform/common/xxx/reports/depscan-report-java.html 👍                                                
            DEBUG    License check and HTML report written to file: /builds/platform/common/xxx/reports/license-java.json,          
                     /builds/platform/common/xxx/reports/license-java.html 👍                                                       
 Traceback (most recent call last):
   File "/usr/local/src/scan", line 716, in <module>
     main()
   File "/usr/local/src/scan", line 684, in main
     report_summary, build_status = analysis.summary(
   File "/usr/local/src/lib/analysis.py", line 106, in summary
     metrics, required_pkgs_found = calculate_depscan_metrics(dep_data)
   File "/usr/local/src/lib/analysis.py", line 75, in calculate_depscan_metrics
     metrics[severity] += 1
 KeyError: 'unspecified'
```
Has there been any recent development that could make this fail?

**Comment by prabhu** [comment]
Can you send a PR?

Here add 3 more keys for unspecified https://github.com/ShiftLeftSecurity/sast-scan/blob/master/lib/analysis.py#L51 

This is happening because some CVE has a severity of unspecified.

**Comment by gitnachogo** [comment]
Sure! I'll send you a PR asap!
