### ISSUE TITLE
utf-8 decode error with certain files

### ISSUE THREAD

**Issue by prabhu** [ShiftLeftSecurity/sast-scan#259]
The attached file is triggering a bug with linecache.

```
>>> linecache.getline("/Users/prabhu/Downloads/Utf8_test.php", 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 298: invalid continuation byte
```

[Utf8_test.php.txt](https://github.com/ShiftLeftSecurity/sast-scan/files/5739455/Utf8_test.php.txt)

**Comment by prabhu** [comment]
```
>>> tokenize.open("/Users/prabhu/Downloads/Utf8_test.php.txt").read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 298: invalid continuation byte
```
